name: Sync Fork

on:
  schedule:
    - cron: '* * * * *' 
  workflow_dispatch: 

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: minkukjo
          base: main
          head: main
